version: '3.0'


networks:
    aws-serv:
      driver: bridge

services:
  localstack:
    image: localstack/localstack:latest
    env_file:
      ./localstack.env
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - ./volumes/localstack/temp:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init.sh:/docker-entrypoint-initaws.d/init.sh
    networks: 
      - aws-serv
