version: "3.0"

volumes:
  mongo-keys:

networks:
  mongo-cluster:
    driver: bridge

services:

####################################
##### PRIMARIO #####################
####################################
  mongo-primary:
    image: mongo:latest
    volumes:
      - ./volumes/data/mongo-data-0:/data/db
      - ./volumes/data/mongo-config-0:/data/configdb
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    networks:
      - mongo-cluster