version: "3.0"

volumes:
  mongo-keys:

networks:
  redis-serv:
    driver: bridge

services:

####################################
##### DATABASE #####################
####################################
  redis-serv:
    image: redis
    command: redis-server --requirepass qwe123
    volumes:
      - ./volumes/redis-data:/data
    ports:
      - 6379:6379
    networks:
      - redis-serv