version: "3.0"

networks:
  kafka-serv:
    driver: bridge

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - kafka-serv
    env_file:
      ./zookeeper.env

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - kafka-serv
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      ./kafka.env

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - kafka-serv
    depends_on:
      - kafka
    ports:
      - 19000:9000
    env_file:
      ./kafdrop.env
